//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaCRUD.CPMX.Data.EF.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CPMXEntities : DbContext
    {
        public CPMXEntities()
            : base("name=CPMXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SPI_CPMX_Asentamiento(Nullable<int> idAsentamiento, string asentamiento, Nullable<int> idMunicipio, Nullable<int> idEstado, Nullable<int> idTipo, string cP)
        {
            var idAsentamientoParameter = idAsentamiento.HasValue ?
                new ObjectParameter("IdAsentamiento", idAsentamiento) :
                new ObjectParameter("IdAsentamiento", typeof(int));
    
            var asentamientoParameter = asentamiento != null ?
                new ObjectParameter("Asentamiento", asentamiento) :
                new ObjectParameter("Asentamiento", typeof(string));
    
            var idMunicipioParameter = idMunicipio.HasValue ?
                new ObjectParameter("IdMunicipio", idMunicipio) :
                new ObjectParameter("IdMunicipio", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            var cPParameter = cP != null ?
                new ObjectParameter("CP", cP) :
                new ObjectParameter("CP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPI_CPMX_Asentamiento", idAsentamientoParameter, asentamientoParameter, idMunicipioParameter, idEstadoParameter, idTipoParameter, cPParameter);
        }
    
        public virtual int SPI_CPMX_Estado(string estado, Nullable<int> id)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPI_CPMX_Estado", estadoParameter, idParameter);
        }
    
        public virtual int SPI_CPMX_Municipio(Nullable<int> idMunicipio, Nullable<int> idEstado, string municipio)
        {
            var idMunicipioParameter = idMunicipio.HasValue ?
                new ObjectParameter("IdMunicipio", idMunicipio) :
                new ObjectParameter("IdMunicipio", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var municipioParameter = municipio != null ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPI_CPMX_Municipio", idMunicipioParameter, idEstadoParameter, municipioParameter);
        }
    
        public virtual int SPI_CPMX_TipoAsentamiento(Nullable<int> idTipo, string tipoAsentamiento)
        {
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            var tipoAsentamientoParameter = tipoAsentamiento != null ?
                new ObjectParameter("TipoAsentamiento", tipoAsentamiento) :
                new ObjectParameter("TipoAsentamiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPI_CPMX_TipoAsentamiento", idTipoParameter, tipoAsentamientoParameter);
        }
    
        public virtual ObjectResult<SPS_CPMX_Asentamientos_Result> SPS_CPMX_Asentamientos(Nullable<int> idEstado, Nullable<int> idMunicipio)
        {
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var idMunicipioParameter = idMunicipio.HasValue ?
                new ObjectParameter("IdMunicipio", idMunicipio) :
                new ObjectParameter("IdMunicipio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CPMX_Asentamientos_Result>("SPS_CPMX_Asentamientos", idEstadoParameter, idMunicipioParameter);
        }
    
        public virtual ObjectResult<SPS_CPMX_AsentamientosCP_Result> SPS_CPMX_AsentamientosCP(string cP)
        {
            var cPParameter = cP != null ?
                new ObjectParameter("CP", cP) :
                new ObjectParameter("CP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CPMX_AsentamientosCP_Result>("SPS_CPMX_AsentamientosCP", cPParameter);
        }
    
        public virtual ObjectResult<SPS_CPMX_EstadoId_Result> SPS_CPMX_EstadoId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CPMX_EstadoId_Result>("SPS_CPMX_EstadoId", idParameter);
        }
    
        public virtual ObjectResult<SPS_CPMX_Estados_Result> SPS_CPMX_Estados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CPMX_Estados_Result>("SPS_CPMX_Estados");
        }
    
        public virtual ObjectResult<SPS_CPMX_MunicipioPorEM_Result> SPS_CPMX_MunicipioPorEM(Nullable<int> idEstado, Nullable<int> idMunicipio)
        {
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var idMunicipioParameter = idMunicipio.HasValue ?
                new ObjectParameter("IdMunicipio", idMunicipio) :
                new ObjectParameter("IdMunicipio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CPMX_MunicipioPorEM_Result>("SPS_CPMX_MunicipioPorEM", idEstadoParameter, idMunicipioParameter);
        }
    
        public virtual ObjectResult<SPS_CPMX_MunicipiosPorEstado_Result> SPS_CPMX_MunicipiosPorEstado(Nullable<int> idEstado)
        {
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CPMX_MunicipiosPorEstado_Result>("SPS_CPMX_MunicipiosPorEstado", idEstadoParameter);
        }
    }
}
